# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(370, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setMinimumSize(QtCore.QSize(370, 300))
        Login.setMaximumSize(QtCore.QSize(500, 300))
        Login.setSizeIncrement(QtCore.QSize(1, 0))
        self.lblLogin = QtWidgets.QLabel(Login)
        self.lblLogin.setGeometry(QtCore.QRect(150, 20, 70, 30))
        self.lblLogin.setMinimumSize(QtCore.QSize(70, 30))
        self.lblLogin.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblLogin.setFont(font)
        self.lblLogin.setObjectName("lblLogin")
        self.layoutWidget = QtWidgets.QWidget(Login)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 311, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblUserName = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUserName.sizePolicy().hasHeightForWidth())
        self.lblUserName.setSizePolicy(sizePolicy)
        self.lblUserName.setMinimumSize(QtCore.QSize(77, 25))
        self.lblUserName.setMaximumSize(QtCore.QSize(100, 25))
        self.lblUserName.setObjectName("lblUserName")
        self.gridLayout.addWidget(self.lblUserName, 0, 0, 1, 1)
        self.lineEditUser = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditUser.sizePolicy().hasHeightForWidth())
        self.lineEditUser.setSizePolicy(sizePolicy)
        self.lineEditUser.setMinimumSize(QtCore.QSize(226, 25))
        self.lineEditUser.setMaximumSize(QtCore.QSize(260, 25))
        self.lineEditUser.setObjectName("lineEditUser")
        self.gridLayout.addWidget(self.lineEditUser, 0, 1, 1, 1)
        self.lblPassword = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPassword.sizePolicy().hasHeightForWidth())
        self.lblPassword.setSizePolicy(sizePolicy)
        self.lblPassword.setMinimumSize(QtCore.QSize(77, 25))
        self.lblPassword.setMaximumSize(QtCore.QSize(100, 25))
        self.lblPassword.setObjectName("lblPassword")
        self.gridLayout.addWidget(self.lblPassword, 1, 0, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPassword.setSizePolicy(sizePolicy)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(226, 25))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(260, 25))
        #self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 1, 1, 1, 1)
        self.btnStartSesion = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartSesion.sizePolicy().hasHeightForWidth())
        self.btnStartSesion.setSizePolicy(sizePolicy)
        self.btnStartSesion.setMinimumSize(QtCore.QSize(226, 25))
        self.btnStartSesion.setMaximumSize(QtCore.QSize(260, 25))
        self.btnStartSesion.setObjectName("btnStartSesion")
        self.gridLayout.addWidget(self.btnStartSesion, 2, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Login)
        self.layoutWidget1.setGeometry(QtCore.QRect(110, 220, 231, 50))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblAccount = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAccount.sizePolicy().hasHeightForWidth())
        self.lblAccount.setSizePolicy(sizePolicy)
        self.lblAccount.setMinimumSize(QtCore.QSize(229, 17))
        self.lblAccount.setMaximumSize(QtCore.QSize(260, 17))
        self.lblAccount.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAccount.setObjectName("lblAccount")
        self.verticalLayout.addWidget(self.lblAccount)
        self.btnCreateAccount = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnCreateAccount.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCreateAccount.sizePolicy().hasHeightForWidth())
        self.btnCreateAccount.setSizePolicy(sizePolicy)
        self.btnCreateAccount.setMinimumSize(QtCore.QSize(229, 25))
        self.btnCreateAccount.setMaximumSize(QtCore.QSize(260, 25))
        self.btnCreateAccount.setObjectName("btnCreateAccount")
        self.verticalLayout.addWidget(self.btnCreateAccount)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.lblLogin.setText(_translate("Login", "Login"))
        self.lblUserName.setText(_translate("Login", "User name:"))
        self.lblPassword.setText(_translate("Login", "Password:"))
        self.btnStartSesion.setText(_translate("Login", "Start sesion"))
        self.lblAccount.setText(_translate("Login", "Do not have an account?"))
        self.btnCreateAccount.setText(_translate("Login", "Create a new account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
