from PySide6 import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(872, 347)
        self.btnEditItem = QtWidgets.QPushButton(Dialog)
        self.btnEditItem.setGeometry(QtCore.QRect(8, 200, 161, 25))
        self.btnEditItem.setObjectName("btnEditItem")
        self.btnNewItem = QtWidgets.QPushButton(Dialog)
        self.btnNewItem.setGeometry(QtCore.QRect(10, 120, 161, 25))
        self.btnNewItem.setObjectName("btnNewItem")
        self.btnOpenItem = QtWidgets.QPushButton(Dialog)
        self.btnOpenItem.setGeometry(QtCore.QRect(10, 160, 161, 25))
        self.btnOpenItem.setObjectName("btnOpenItem")
        self.lineEditSearch = QtWidgets.QLineEdit(Dialog)
        self.lineEditSearch.setGeometry(QtCore.QRect(190, 50, 191, 25))
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.btnSearch = QtWidgets.QPushButton(Dialog)
        self.btnSearch.setGeometry(QtCore.QRect(390, 50, 91, 25))
        self.btnSearch.setObjectName("btnSearch")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(190, 80, 631, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.btnStartSesion = QtWidgets.QPushButton(Dialog)
        self.btnStartSesion.setGeometry(QtCore.QRect(10, 80, 161, 25))
        self.btnStartSesion.setObjectName("btnStartSesion")
        self.lblWelcome = QtWidgets.QLabel(Dialog)
        self.lblWelcome.setGeometry(QtCore.QRect(660, 10, 171, 17))
        self.lblWelcome.setObjectName("lblWelcome")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnEditItem.setText(_translate("Dialog", "Edit selected item"))
        self.btnNewItem.setText(_translate("Dialog", "Create new item"))
        self.btnOpenItem.setText(_translate("Dialog", "Open selected item"))
        self.lineEditSearch.setPlaceholderText(_translate("Dialog", "Type a keyword to search"))
        self.btnSearch.setText(_translate("Dialog", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "User"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "URL"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Category"))
        self.btnStartSesion.setText(_translate("Dialog", "Start sesion"))
        self.lblWelcome.setText(_translate("Dialog", "Welcome..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
